# Site settings
title: Piotr Próchnicki
name: Piotr Próchnicki

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: GitHub
#   url: https://github.com/PiotrIT2015
# - title: Linkedin
#   url: https://www.linkedin.com/in/piotr-prochnicki
# - title: Facebook
#   url: https://facebook.com/piotr.prochnicki.526
# - title: Twitter
#   url: https://twitter.com/PiotrProchnicki

#Social media   
twitter_username:
 - PiotrProchnicki
instagram_username:
 - pprochni
linkedin_username:
 - piotr-prochnicki
github_username:
 - PiotrIT2015
facebook_username:
 - piotr.prochnicki.526
gitlab_username:
 - PiotrIT2017
dockerhub_username:
 - piotrit2015
 

#Any buzzword skills you want to include
skills:
 - Java  
 - GIT
 - Android
 - Gradle
 - Spring
 - SQL
 - HTML
 - CSS
 - Linux
 - Windows
 - Docker
 - Hibernate

#Work experience is required
roles:
 - title: Office worker
   start: September 2020
   end: December 2020
   employer: Paweł Samolej Grupa Center
   description: Complete the marketing of all items that needed to be completed before the holiday shopping season in an automated Shopper environment.
 - title: Office Administrative Employee
   start: November 2018
   end: June 2020
   employer: HR team Sp. z.o.o.
   description: Segregation, recording and creating documentation. Cooperating with other organizational units. Handling of mail. Entering data to a computer. Office service.
 - title: Cisco Services Engineer Intern
   start: July 2017
   end: September 2017
   employer: CISCO SYSTEMS, Krakow, Poland
   description: Achieve practical knowledge in the field of computer networks and programming language Python
 - title: IT Specialist
   start: March 2017
   end: April 2017
   employer: COGITO, Association for the development of psychiatry and environmental care, Krakow, Poland
   description: I took care of all IT devices. My daily work focused on solving different problems with local networks and systems.
 - title: Office Technican
   start: October 2016
   end: December 2016
   employer: Office Computing, City Office, Krakow, Poland
   description: Accounting for hardware and software. Replacing the printer's toner. IT services for conference rooms.
 - title: Serviceman
   start: July 2015
   end: October 2015
   employer: Office Computing, Malopolska Regional Office, Krakow, Poland
   description: Execution of current hungry signaled by IT system users. Service support phone service calls.

#Education is required
education:
 - level: Master of Science
   date: March 2017
   subject: Applied Computer Sciences
   school: University of Science and Technology, Krakow, Poland
 - level: Bachelor of Science
   date: March 2015
   subject: Medical Physics
   school: University of Science and Technology, Krakow, Poland

#This section is optional (as is the image link below)
apps:
 - name: Reminder
   url: https://github.com/PiotrIT2015/Reminder
   description: app helps to remember about shops
 - name: HealthMonitor
   url: https://github.com/PiotrIT2015/HealthMonitor
   description: app helps maintain balance in i.e.time of COVID-19
 - name: Shipper
   url: https://github.com/PiotrIT2015/Shipper
   description: app helps counting time demanded for shopping from Reminder
 - name: KrkCode
   url: https://github.com/PiotrIT2015/KrkCode
   description: project frontend app for Krkbalanceguard.
   
#List of interesting Github repo/projects to include - optional
github:
 - PiotrIT2015/Cisco
 - PiotrIT2015/thesis
 - PiotrIT2015/Krkbalanceguard
 - PiotrIT2015/Codility

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/8010152/piotr-pr%C3%B3chnicki

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I've develop Java application sinc study.
   <strong>Spring</strong>: I've develop microservices based on Spring sinc I started create project balanceguard.
   <strong>Docker</strong>: I used Docker in balanceguard.
   <strong>Android</strong>: I was developing apps in this technology i.e. through useme portal<br/><br/>
