# Site settings
title: Piotr Próchnicki
name: Piotr Próchnicki

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: GitHub
#   url: https://github.com/PiotrIT2015
# - title: Linkedin
#   url: https://www.linkedin.com/in/piotr-prochnicki
# - title: Facebook
#   url: https://facebook.com/piotr.prochnicki.526
# - title: Twitter
#   url: https://twitter.com/PiotrProchnicki

#Social media
hobby_username: piotr-prochnicki,69881
linkedin_username: piotr-prochnicki
linkedin_craft_1: 10150707
linkedin_craft_2: krk-1mw
linkedin_craft_3: lowcy-kariery
linkedin_craft_4: poland-people-linkedin
x_craft: PiotrProchnicki
github_username: PiotrIT2015
gitlab_username: PiotrIT2017
dockerhub_username: piotrit2015

#Any buzzword skills you want to include
skills:
 - Cybersecurity
 - SIEM
 - Network Security
 - Threat Detection
 - Incydent Response
 - Linux
 - Docker
 - Python

#Work experience is required
roles:
 - title: DevOps Engineer
   start: June 2023
   end: September 2023
   employer: HXS Sp. z.o.o. Sp. k.
   description: Debugging the code(<strong>PHP</strong>). Reading the documentation.
 - title: Cisco Services Engineer Intern
   start: July 2017
   end: September 2017
   employer: CISCO SYSTEMS, Krakow, Poland
   description: Achieve practical knowledge in the field of computer networks and <strong>Python</strong>
 - title: Office Technican
   start: October 2016
   end: December 2016
   employer: Office Computing, City Office, Krakow, Poland
   description: Accounting for hardware and software. Replacing the printer's toner. IT services for conference rooms.
 - title: Serviceman
   start: July 2015
   end: October 2015
   employer: Office Computing, Malopolska Regional Office, Krakow, Poland
   description: Execution of current hungry signaled by IT system users. Service support phone service calls.

#Education is required
education:
 - level: Master of Science
   date: March 2017
   subject: Applied Computer Sciences
   school: University of Science and Technology(AGH), Krakow, Poland
 - level: Bachelor of Science
   date: March 2015
   subject: Medical Physics
   school: University of Science and Technology(AGH), Krakow, Poland

#This section is optional (as is the image link below)
apps:
 - name: WW-P-mobile
   url: https://github.com/PiotrIT2015/WW-P-mobile
   description: This is an app could be use as mobile store flyer.
 - name: WW-P-mobile-web
   url: https://pcamobileapp.azurewebsites.net/
   description: This is an app could be use as mobile store flyer.
 - name: WW-P-sounds-help
   url: https://github.com/PiotrIT2015/WW-P-sounds-help
   description: This is an android app which could help disabled people cope with listen disability.

#List of interesting Github repo/projects to include - optional
github:
 - PiotrIT2015/white-weed-playcraft
 - PiotrIT2015/OS-WW-P
 - PiotrIT2015/NetworkMonitor
 - PiotrIT2015/PHPYoutubeclone
 - PiotrIT2015/EthicalHacker
 - PiotrIT2015/CCNA
 - PiotrIT2015/Krk
 - PiotrIT2015/thesis
 - PiotrIT2015/CV-P
 - PiotrIT2015/chess-break

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/8010152/piotr-pr%C3%B3chnicki

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I've developed Java application since study.
   <strong>Python</strong>: I've developed Python application since my thesis.
   <strong>Docker</strong>: I've developed Docker since my last IT internship.
   <strong>Android</strong>: I was developing several apps in this technology which you could see above.<br/><br/>